title: STE in JtD
description: Review text of MT done using STE standards
theme: just-the-docs

url: https://Lipkowski.github.io/JustTheDocs_PL

aux_links:
  Template Repository: https://github.com/Lipkowski/JustTheDocs_PL
